#!/usr/bin/env bash

set -e

if [ -e '/usr/bin/lscpu' ]; then
  /usr/bin/lscpu | grep 'L2 cache' | awk '{print $3}' | sed 's!K$!*1024!'
else
  # The Mac L2 cache count is per-core
  echo \
    $(system_profiler SPHardwareDataType | grep 'L2 Cache' | awk '{print $5$6}' | sed 's!KB$!*1024!;s!MB$!*1024*1024!') \
    '*' \
    $(./scripts/count-nproc)
fi

