#!/usr/bin/env bash

set -e

if [ -e '/usr/bin/lscpu' ]; then
  result=$(/usr/bin/lscpu | grep 'L2 cache' | awk '{print $3}' | sed 's!K$!*1024!')
  echo $(($result * 1))
else
  # The Mac L2 cache count is per-core
  nproc=$(sysctl -n hw.physicalcpu)
  mb=$(system_profiler SPHardwareDataType | grep 'L2 Cache' | awk '{print $5$6}' | sed 's!KB$!*1024!;s!MB$!*1024*1024!')
  result=$(($mb * $nproc))
  echo $result
fi

